In [23]:
%pip install pandas

import pandas as pd
import numpy as np
import datetime as dt
%pip install yfinance

import yfinance as yf

Requirement already satisfied: pandas in ./.venv-1/lib/python3.13/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in ./.venv-1/lib/python3.13/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv-1/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv-1/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: yfinance in ./.venv-1/lib/python3.13/site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (6.1.3)
Requirement already satisfied: multitasking>=0.0.7 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (2.5.3)
Requirement already satisfied: pandas>=1.3.0 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (3.0.6)
Requirement already satisfied: peewee>=3.16.2 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (4.5.1)
Requirement already satisfied: platformdirs>=2.0.0 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (4.11.11)
Requirement already satisfied: protobuf>=3.19.0 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (7.36.2)
Requirement already satisfied: pytz>=2022.5 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: requests>=2.31 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (2.34.2)
Requirement already satisfied: websockets>=13.0 in ./.venv-1/lib/python3.13/site-packages (from yfinance) (17.1)
Requirement already satisfied: soupsieve>=1.6.1 in ./.venv-1/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv-1/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in ./.venv-1/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in ./.venv-1/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in ./.venv-1/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv-1/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv-1/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv-1/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in ./.venv-1/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv-1/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.8.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [24]:
startdate = dt.datetime(2021,1,1)
enddate = dt.datetime(2026,9,21)

In [25]:
kpittech = yf.Ticker("KPITTECH.NS")

In [26]:
kpittech_df = kpittech.history(start = startdate, end = enddate)
kpittech_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-01-01 00:00:00+05:30,136.231977,143.521486,136.231977,138.935364,2734406,0.0,0.0
2021-01-04 00:00:00+05:30,140.190495,142.893896,137.921580,140.431870,2237108,0.0,0.0
2021-01-05 00:00:00+05:30,137.921605,141.928422,136.425078,139.128479,1376388,0.0,0.0
2021-01-06 00:00:00+05:30,139.273283,140.431879,128.701068,131.694107,1817053,0.0,0.0
2021-01-07 00:00:00+05:30,133.238926,137.100924,129.473484,130.632080,775346,0.0,0.0
...,...,...,...,...,...,...,...
2026-09-14 00:00:00+05:30,553.750000,553.750000,553.750000,553.750000,0,0.0,0.0
2026-09-15 00:00:00+05:30,560.000000,580.950012,560.000000,563.000000,4090759,0.0,0.0
2026-09-16 00:00:00+05:30,563.000000,566.400024,553.099976,555.000000,831708,0.0,0.0
2026-09-17 00:00:00+05:30,556.200012,560.950012,552.500000,559.299988,599882,0.0,0.0
2026-09-18 00:00:00+05:30,559.299988,559.500000,532.000000,532.000000,3944020,0.0,0.0

In [27]:
kpittech_df = kpittech_df.reset_index()

kpittech_df['Date'] = pd.to_datetime(kpittech_df['Date']).dt.tz_localize(None)

kpittech_df.reset_index(drop=True, inplace=True)

kpittech_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-01,136.231977,143.521486,136.231977,138.935364,2734406,0.0,0.0
1,2021-01-04,140.190495,142.893896,137.921580,140.431870,2237108,0.0,0.0
2,2021-01-05,137.921605,141.928422,136.425078,139.128479,1376388,0.0,0.0
3,2021-01-06,139.273283,140.431879,128.701068,131.694107,1817053,0.0,0.0
4,2021-01-07,133.238926,137.100924,129.473484,130.632080,775346,0.0,0.0
...,...,...,...,...,...,...,...,...
1412,2026-09-14,553.750000,553.750000,553.750000,553.750000,0,0.0,0.0
1413,2026-09-15,560.000000,580.950012,560.000000,563.000000,4090759,0.0,0.0
1414,2026-09-16,563.000000,566.400024,553.099976,555.000000,831708,0.0,0.0
1415,2026-09-17,556.200012,560.950012,552.500000,559.299988,599882,0.0,0.0
1416,2026-09-18,559.299988,559.500000,532.000000,532.000000,3944020,0.0,0.0

In [28]:
kpittech_df.to_csv('kpittech_stock_data.csv', index=False)

In [29]:
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf

def get_stock_data(ticker, start_date, end_date, filename):
    
    # Download stock data
    stock = yf.Ticker(ticker)
    stock_df = stock.history(
        start=start_date,
        end=end_date
    )
    
    # Reset Date index
    stock_df = stock_df.reset_index()
    
    # Remove timezone from Date
    stock_df['Date'] = pd.to_datetime(
        stock_df['Date']
    ).dt.tz_localize(None)
    
    # Reset index
    stock_df.reset_index(drop=True, inplace=True)
    
    # Export to CSV
    stock_df.to_csv(filename, index=False)
    
    return stock_df

In [30]:
startdate = dt.datetime(2021, 1, 1)

enddate = dt.datetime(2026, 9, 21)

In [31]:
persistent_df = get_stock_data(

    "PERSISTENT.NS",

    startdate,

    enddate,

    "kpittech_stock_data.csv"

)

persistent_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-01,719.707364,731.146422,704.359985,713.773376,365382,0.0,0.0
1,2021-01-04,717.324248,726.856796,709.269233,724.378357,373966,0.0,0.0
2,2021-01-05,731.146441,750.688165,720.660638,738.986938,668318,0.0,0.0
3,2021-01-06,752.737737,762.127274,720.970506,734.411377,298186,0.0,0.0
4,2021-01-07,743.514909,743.514909,720.184021,724.568970,522426,0.0,0.0
...,...,...,...,...,...,...,...,...
1411,2026-09-11,5469.000000,5545.500000,5444.500000,5516.000000,335360,0.0,0.0
1412,2026-09-14,5516.000000,5516.000000,5516.000000,5516.000000,0,0.0,0.0
1413,2026-09-15,5654.000000,5759.000000,5456.500000,5477.500000,812335,0.0,0.0
1414,2026-09-16,5522.000000,5529.500000,5390.500000,5440.000000,412053,0.0,0.0
1415,2026-09-18,5476.000000,5500.000000,5389.000000,5416.000000,494682,0.0,0.0

In [32]:
persistent_df.to_csv('persistent_stock_data.csv', index=False)

In [33]:
hcltech_df= get_stock_data(

    "HCLTECH.NS",

    startdate,

    enddate,

    "hcltech_stock_data.csv"

)

hcltech_df.to_csv('hcltech_stock_data.csv', index=False)

In [34]:
techmahindra_df= get_stock_data(

    "TECHM.NS",

    startdate,

    enddate,

    "techmahindra_stock_data.csv"

)

techmahindra_df.to_csv('techmahindra_stock_data.csv', index=False)

In [35]:

coforge_df= get_stock_data(

    "COFORGE.NS",

    startdate,

    enddate,

    "coforge_stock_data.csv"

)

coforge_df.to_csv('coforge_stock_data.csv', index=False)

In [36]:
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf

In [37]:
startdate = dt.datetime(2021, 1, 1)
enddate = dt.datetime(2026, 9, 21)

In [38]:
def get_stock_data(ticker, start_date, end_date, filename):
    
    stock = yf.Ticker(ticker)
    
    stock_df = stock.history(
        start=start_date,
        end=end_date
    )
    
    stock_df = stock_df.reset_index()
    
    stock_df['Date'] = pd.to_datetime(
        stock_df['Date']
    ).dt.tz_localize(None)
    
    stock_df.reset_index(drop=True, inplace=True)
    
    stock_df.to_csv(filename, index=False)
    
    return stock_df

In [39]:
stocks = {
    "TATAELXSI": "TATAELXSI.NS",
    "HDFCBANK": "HDFCBANK.NS",
    "SUNPHARMA": "SUNPHARMA.NS",
    "LT": "LT.NS",
    "NTPC": "NTPC.NS",
    "HAL": "HAL.NS",
    "TITAN": "TITAN.NS",
    "BHARTIARTL": "BHARTIARTL.NS",
    "MARUTI": "MARUTI.NS",
    "ITC": "ITC.NS"
}

In [40]:
stock_data = {}

for name, ticker in stocks.items():
    
    filename = f"{name}_stock_data.csv"
    
    stock_data[name] = get_stock_data(
        ticker,
        startdate,
        enddate,
        filename
    )
    
    print(f"{name} downloaded successfully")

TATAELXSI downloaded successfully
HDFCBANK downloaded successfully
SUNPHARMA downloaded successfully
LT downloaded successfully
NTPC downloaded successfully
HAL downloaded successfully
TITAN downloaded successfully
BHARTIARTL downloaded successfully
MARUTI downloaded successfully
ITC downloaded successfully